MARKETProtocol/MARKETProtocol

test/MarketContractOraclize.js, test/utility.js
This solves all the extended tests required in #4
=> Tests for MarketContractOraclize

test/CollateralToken.js, test/MarketCollateralPool.js, test/MarketContractOraclize.js, test/OrderLib.js, test/utility.js
This basically updates the tests to use some of the safer features of es6 (mostly the let and const statements).
And also does some minor refactoring.
=> Update test to es6

contracts/MarketCollateralPool.sol, test/MarketCollateralPool.js
Just some requires and a 'if' showing as branch not covered
=> bring test coverage for MarketCollateralPool.sol to 100% issue #28

docker-compose.yml
#33 - should be resolved.  I followed @cryptomental 's recipe for success!
=> Docker image change #33

contracts/oraclize/MarketContractOraclize.sol, migrations/2_deploy_contracts.js, package.json
=> Removed prefund

makefile
this branch adds a makefile which captures key commands and dependencies.
=> initialized makefile

.travis.yml, docker-compose.yml
Modify Ethereum bridge container entrypoint to wait until Ethereum
node is fully initialized and accepts connections.
CI, docker.
Tested on CI.
Fixes: #78
=> docker-compose.yml: Fix intermittent CI failures.

contracts/MarketContract.sol, contracts/MarketContractRegistry.sol, contracts/MarketContractRegistryInterface.sol, contracts/oraclize/MarketContractFactoryOraclize.sol, contracts/oraclize/MarketContractOraclize.sol, contracts/oraclize/TestableMarketContractFactoryOraclize.sol, contracts/tokens/UpgradeableTokenMock.sol, migrations/2_deploy_contracts.js, package-lock.json, package.json, test/GasOraclize.js, test/MarketCollateralPool.js, test/MarketContractOraclize.js, test/MarketContractRegistry.js, test/OrderLib.js, test/helpers/TraderHelper.js
Since upgrading solidity and a few other optimizations that have recently happened, the gas costs of deploying the MarketContractOraclize.sol have reduced significantly.  This now allows us to to get back to the factory idea, where a factory creates and deploy the MarketContractOraclize.sol contracts and is the one to add them to the whitelist
The benefit of there is no need for external verification since we know the contracts for sure have been deployed via our factory, via our source code.  
The only piece still not able to be combined is deploying the MarketCollateralPool into a single transaction as this still runs out of gas on the truffle gas limits of ~6.7 million.
This PR is mainly to start the discussion around merging this.  Some tests, sepcifically the ones around the …
=> Create factory now that gas costs are lowered

README.md
Add instructions to README.md on how to run tests with coverage enabled using Docker
Docs
Refs: #86
=> README.md: Add instructions on how to run tests with coverage enabled.

.travis.yml, package.json, scripts/travis_npm_compile.sh
Renamed @marketprotocol/solidity and created automated deployment from master commits with tags to npm.
Fixes: #95
=> mod packages for test auto deploy to npm

contracts/MarketContract.sol, test/MarketContractOraclize.js
Disallow self-trade.
Tests
Wrote tests
Fixes #93
=> Disallow self-trade

contracts/MarketContract.sol, contracts/MarketContractRegistryInterface.sol, contracts/factories/MarketCollateralPoolFactory.sol, contracts/factories/MarketCollateralPoolFactoryInterface.sol, contracts/libraries/OrderLib.sol, contracts/mocks/OrderLibMock.sol, contracts/oraclize/MarketContractFactoryOraclize.sol, contracts/oraclize/MarketContractOraclize.sol, contracts/oraclize/TestableMarketContractFactoryOraclize.sol, contracts/oraclize/TestableMarketContractOraclize.sol, contracts/tokens/MarketToken.sol, migrations/2_deploy_contracts.js, test/GasOraclize.js, test/MarketCollateralPool.js, test/MarketContractOraclize.js, test/MarketContractRegistry.js, test/OrderLib.js
Creates a collateral pool factory that streamlines deployment, adds more security and reduces number of needed transactions for a user to deploy a contract (down to 2 vs 3) fixes #94 
Also fixes some style issues as well as the deprecate `keccak` calls without using `abi.encodePacked`
protocol, docs will need to be updated as well as dApp
tests updated and passing with new migration script.
fixes #94
=> Feature/collateral factory #94

contracts/MarketContract.sol, package-lock.json
=> Adds price to OrderFilled event

contracts/MarketCollateralPool.sol, test/MarketCollateralPool.js, test/MarketContractOraclize.js
Adds getter functions to expose structs which cannot be returned from solidity
ran all tests, and added some new
fixes #108
=> expose functions in order to be able to query user position data 

contracts/MarketCollateralPool.sol, test/MarketCollateralPool.js, test/MarketContractOraclize.js, test/helpers/TraderHelper.js
refactor for more clarity
Collateral Pool and corresponding tests
fixes #117
=> refactor getUserAccountBalance to getUserUnallocatedBalance

contracts/MarketCollateralPool.sol, test/MarketCollateralPoolAccounting.js, test/MarketContractOraclize.js
Fixes issues with position accounting and reporting
more testing added!
fixes #136
=> fixes #136 due to sign error, adds additional testing for accounting

contracts/MarketCollateralPool.sol, contracts/MarketContract.sol, contracts/MarketTradingHub.sol, contracts/chainlink/MarketContractChainLink.sol, contracts/chainlink/MarketContractFactoryChainLink.sol, contracts/libraries/OrderLib.sol, contracts/mocks/OrderLibMock.sol, contracts/oraclize/MarketContractFactoryOraclize.sol, contracts/oraclize/MarketContractOraclize.sol, contracts/oraclize/TestableMarketContractFactoryOraclize.sol, contracts/oraclize/TestableMarketContractOraclize.sol, migrations/1_initial_migration.js, migrations/2_market_contracts.js, migrations/3_oraclize_contracts.js, migrations/4_chainlink_contracts.js, test/MarketCollateralPool.js, test/MarketCollateralPoolAccounting.js, test/MarketContractOraclize.js, test/MarketContractOraclizeCallBack.js, test/MarketContractRegistry.js, test/OrderLib.js, test/helpers/TraderHelper.js, test/libraries/TestOrderLib.sol
Creates a trading hub to remove all trading logic from MarketContracts that are being deployed constantly.
There is significant gas savings to be had with this architecture
Everything
=> Feature/trading hub - re-opened due to branch of branch

.solcover.js, migrations/2_market_contracts.js, migrations/3_oraclize_contracts.js, migrations/4_chainlink_contracts.js, test/chainlink/OracleHubChainLink.js
Testing for our new Oracle Hub
tests
No functional changes, only tests
fixes #133
=> adds tests for OracleHubChainlink

test/chainlink/MarketContractChainLink.js
adds test for MarketContractChainLink
tests
fixes #131
=> adds test for MarketContractChainLink

test/chainlink/MarketContractFactoryChainLink.js
adds testing for MarketContractFactoryChainLink
tests
fixes #132
=> adds testing for MarketContractFactoryChainLink

migrations/4_chainlink_contracts.js
Links MathLib to MarketContractFactoryChainLink in migration, hence fixing build/migration error
Fixes: #164
=> Fix: Truffle Migration error

contracts/libraries/MathLib.sol, test/libraries/TestMathLib.sol
Tests and Fixes MathLib.calculateTotalCollateral
Fixes: #157
=> Feature: Test calculate total collateral

contracts/MarketCollateralPool.sol, contracts/chainlink/MarketContractFactoryChainLink.sol, contracts/oraclize/MarketContractFactoryOraclize.sol, contracts/oraclize/TestableMarketContractFactoryOraclize.sol, migrations/2_market_contracts.js, migrations/3_oraclize_contracts.js, migrations/4_chainlink_contracts.js
Fixes our migration issues for the moment.  This is kind of hacaky, but will allow @perfectmak and @eswarasai to move forward while I work on the gas issues more holistically.
=> fixes migrations issues

package-lock.json, package.json, test/MarketCollateralPool.js, test/tokens/PositionToken.js, test/utility.js
Added tests for PositionToken
Fixes: #158
=> Added tests for PositionToken

contracts/oraclize/OracleHubOraclize.sol, test/MarketContract.js, test/chainlink/OracleHubChainLink.js, test/oraclize/OracleHubOraclize.js, test/utility.js
Test Oracle hub features
Also adds tests for the base MarketContracts methods.
OracleHubOraclize tests
Fixes: #169
Fixes: #170
=> Feature: oracle hub oraclize test

contracts/tokens/PositionToken.sol, package.json
Hard codes decimals to 5 in our position tokens
=> Fix/decimal issues#183

Dockerfile, docker-compose.yml
Updates docker image to patched oraclize bridge.
Peg truffle version to 4.1.14
=> updated docker images with bug fix to oraclize bridge

README.md
=> Updated the readme to include a recommended node version and nvm.

contracts/MarketCollateralPool.sol, contracts/MarketContract.sol, contracts/MarketContractRegistry.sol, contracts/MarketContractRegistryInterface.sol, contracts/Migrations.sol, contracts/libraries/MathLib.sol, contracts/libraries/StringLib.sol, contracts/mpx/MarketContractFactoryMPX.sol, contracts/mpx/MarketContractMPX.sol, contracts/tokens/CollateralToken.sol, contracts/tokens/InitialAllocationCollateralToken.sol, contracts/tokens/MarketToken.sol, contracts/tokens/PositionToken.sol, contracts/tokens/UpgradableToken.sol, contracts/tokens/UpgradeableTarget.sol, contracts/tokens/UpgradeableTokenMock.sol, migrations/2_market_contracts.js, package.json, test/MarketCollateralPool.js, test/MarketContract.js, test/mpx/MarketContractFactoryMPX.js, test/mpx/MarketContractMPX.js, test/tokens/PositionToken.js, test/utility.js
- Adds variable fee structure
- locks solidity version
#203
=> Feature/variable fee#203

test/MarketCollateralPool.js, test/utility.js
This adds tests for two major scenarios
- Test settlementDelay() before settleAndClose
- Tests variable fee structure
Fixes: #202 
Fixes: #205
=> Test settlement delay and variable fees structure

contracts/MarketContract.sol, contracts/mpx/MarketContractFactoryMPX.sol, contracts/mpx/MarketContractMPX.sol, test/MarketCollateralPool.js, test/mpx/MarketContractMPX.js
- Seperates oracle from aribtrator (owner)
- adds testing for all lines missing (AFAIK)
#208 #210
=> Testing and owner vs oracle

package-lock.json, package.json, test/utility.js
=> Use Web3 Core modules to invoke evm methods

contracts/mpx/MarketContractFactoryMPX.sol
=> locks down deployMarketContractMPX to only deployable by the owner.
